version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.6-browsers
    steps:
      - checkout
      - run:
          name: Verify Artifacts
          command: cd eslint-config && yarn test && cd ../prettier-config && yarn test

workflows:
  version: 2
  react_library:
    jobs:
      - build
